# Site settings
title: Srinath Sridhar
email: ssridhar@mpi-inf.mpg.de
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://mpi-inf.mpg.de/~ssridhar/blog"
url: "http://mpi-inf.mpg.de/~ssridhar/blog"
twitter_username: srinath1905
github_username:  srinath1905

destination: ../www/blog/

# Build settings
markdown: kramdown
permalink: pretty
