# Site settings
title: Srinath Sridhar
email: srinaths@umich.edu
description: "Srinath Sridhar: Blog"
baseurl: "http://mpi-inf.mpg.de/~ssridhar"
url: "http://mpi-inf.mpg.de/~ssridhar/blog"
twitter_username: srinath1905
github_username:  srinath1905

# Build settings
markdown: kramdown
permalink: :year/:title.html

destination: ../homepage/blog/
